

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                namespace Animation {
                    ref class Storyboard;
                }
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class Grid;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                ref class CompositeTransform;
            }
        }
    }
}

namespace Retro_Inifinty_Demo
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ gameLogoStoryboard_;
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ btnClickStoryboard_;
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ cloudStoryboard_;
        private: ::Windows::UI::Xaml::Controls::Image^ bckImage_;
        private: ::Windows::UI::Xaml::Controls::Grid^ contentGrd_;
        private: ::Windows::UI::Xaml::Controls::Grid^ mainMenuGrid_;
        private: ::Windows::UI::Xaml::Controls::Grid^ gameLogoGrid_;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ exitBtnTransform;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ loadBtnTransform;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ settingsBtnTransform;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ helpBtnTransform;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ videoBtnTransform;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ continueBtnTransform;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ newGmBtnTransform;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ stroeBtnTransform;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ trans;
        private: ::Windows::UI::Xaml::Controls::Image^ gmLogo_;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ trans1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ mainMenu_;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ cloud6;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ cloud5;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ cloud4;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ cloud3;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ cloud2;
        private: ::Windows::UI::Xaml::Media::CompositeTransform^ cloud1;
    };
}

