

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainPage.xaml.h"




void ::Retro_Inifinty_Demo::MainPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///MainPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Storyboard named 'gameLogoStoryboard_'
    gameLogoStoryboard_ = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gameLogoStoryboard_"));
    // Get the Storyboard named 'btnClickStoryboard_'
    btnClickStoryboard_ = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"btnClickStoryboard_"));
    // Get the Storyboard named 'cloudStoryboard_'
    cloudStoryboard_ = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cloudStoryboard_"));
    // Get the Image named 'bckImage_'
    bckImage_ = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"bckImage_"));
    // Get the Grid named 'contentGrd_'
    contentGrd_ = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"contentGrd_"));
    // Get the Grid named 'mainMenuGrid_'
    mainMenuGrid_ = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"mainMenuGrid_"));
    // Get the Grid named 'gameLogoGrid_'
    gameLogoGrid_ = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gameLogoGrid_"));
    // Get the CompositeTransform named 'exitBtnTransform'
    exitBtnTransform = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"exitBtnTransform"));
    // Get the CompositeTransform named 'loadBtnTransform'
    loadBtnTransform = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"loadBtnTransform"));
    // Get the CompositeTransform named 'settingsBtnTransform'
    settingsBtnTransform = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"settingsBtnTransform"));
    // Get the CompositeTransform named 'helpBtnTransform'
    helpBtnTransform = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"helpBtnTransform"));
    // Get the CompositeTransform named 'videoBtnTransform'
    videoBtnTransform = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"videoBtnTransform"));
    // Get the CompositeTransform named 'continueBtnTransform'
    continueBtnTransform = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"continueBtnTransform"));
    // Get the CompositeTransform named 'newGmBtnTransform'
    newGmBtnTransform = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"newGmBtnTransform"));
    // Get the CompositeTransform named 'stroeBtnTransform'
    stroeBtnTransform = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"stroeBtnTransform"));
    // Get the CompositeTransform named 'trans'
    trans = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"trans"));
    // Get the Image named 'gmLogo_'
    gmLogo_ = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gmLogo_"));
    // Get the CompositeTransform named 'trans1'
    trans1 = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"trans1"));
    // Get the TextBlock named 'mainMenu_'
    mainMenu_ = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"mainMenu_"));
    // Get the CompositeTransform named 'cloud6'
    cloud6 = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cloud6"));
    // Get the CompositeTransform named 'cloud5'
    cloud5 = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cloud5"));
    // Get the CompositeTransform named 'cloud4'
    cloud4 = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cloud4"));
    // Get the CompositeTransform named 'cloud3'
    cloud3 = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cloud3"));
    // Get the CompositeTransform named 'cloud2'
    cloud2 = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cloud2"));
    // Get the CompositeTransform named 'cloud1'
    cloud1 = safe_cast<::Windows::UI::Xaml::Media::CompositeTransform^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cloud1"));
}

void ::Retro_Inifinty_Demo::MainPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Retro_Inifinty_Demo::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Retro_Inifinty_Demo::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Retro_Inifinty_Demo::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Retro_Inifinty_Demo::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Retro_Inifinty_Demo::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Retro_Inifinty_Demo::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Retro_Inifinty_Demo::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Retro_Inifinty_Demo::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

